# Generated by Django 3.1.3 on 2021-01-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210105_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='article_fk',
        ),
    ]
